/**
 * Seed export — the write-back half of the operating model (ADR-0011, RQ-0004, ADR-0018). Serializes
 * the OAuth clients currently in Mongo into a seed.yaml-shaped document (one deployment = one realm, so
 * a flat `clients` / `users` list, no tenant layer), so changes made through the admin console / API can
 * be captured back into version-controlled config (commit the output) and survive a rebuild-from-seed.
 * The inverse of `scripts/seed.ts`.
 *
 *   cd service
 *   npm run dump-seed                       # whole DB → stdout
 *   npm run dump-seed -- --out=../config/seed.yaml
 *   npm run dump-seed -- --include-users    # also emit users (with ${ENV} password placeholders)
 *
 * SECRETS ARE NOT RECOVERABLE. Client secrets and user passwords are stored only as one-way hashes,
 * so they cannot be exported:
 *   - Clients are dumped WITHOUT `secret`. Re-running seed against the SAME db preserves each client's
 *     existing secretHash (the loader only writes secretHash when `secret:` is present), so this is a
 *     lossless round-trip for live data. For a FRESH-db rebuild, a confidential client with no secret
 *     would come up with no usable secret — add a `secret: ${ENV_VAR}` to its entry first. The script
 *     warns about every confidential client it dumps without a secret.
 *   - Users are omitted by default (passwords unrecoverable + emails are PII). `--include-users` emits
 *     them with `password: ${SEED_<USER>_PASSWORD}` placeholders you must set in the env before loading.
 */
import process from 'process';
import { writeFileSync } from 'fs';
import { fileURLToPath } from 'url';
import { stringify } from 'yaml';
import { getMasterConnection, disconnect } from '../src/utils/db.js';
import { makeModels } from '../src/models/index.js';

interface Flags { out?: string; includeUsers: boolean }

function parseFlags(): Flags {
  const args = process.argv.slice(2);
  const get = (k: string) => args.find((a) => a.startsWith(`--${k}=`))?.slice(k.length + 3);
  return { out: get('out'), includeUsers: args.includes('--include-users') };
}

/** Minimal shapes the builder needs from the lean Mongo docs (kept loose so tests need no real models). */
export interface DumpClient { _id: string; name?: string; grantTypes?: string[]; audience?: string; redirectUris?: string[]; scopes?: string[]; isConfidential?: boolean; subject?: string; claims?: Record<string, unknown> }
export interface DumpUser { email: string; status?: string; roles?: string[] }

/** Drop undefined / empty-array keys so the emitted YAML stays close to a hand-written seed file. */
function compact<T extends Record<string, unknown>>(obj: T): Partial<T> {
  const out: Record<string, unknown> = {};
  for (const [k, v] of Object.entries(obj)) {
    if (v === undefined || v === null) continue;
    if (Array.isArray(v) && v.length === 0) continue;
    out[k] = v;
  }
  return out as Partial<T>;
}

/** Stable, uppercase env-var name for a user's password placeholder. */
export function passwordEnvVar(email: string): string {
  const slug = (s: string) => s.replace(/[^a-zA-Z0-9]+/g, '_').replace(/^_+|_+$/g, '').toUpperCase();
  return `SEED_${slug(email.split('@')[0])}_PASSWORD`;
}

/**
 * Pure transform: turn live clients/users into seed.yaml-shaped objects, plus any operator warnings.
 * Exported (no I/O) so it round-trips through parseSeedConfig under test.
 */
export function buildSeed(
  clients: DumpClient[],
  users: DumpUser[],
  opts: { includeUsers: boolean }
): { clients: Record<string, unknown>[]; users: Record<string, unknown>[]; warnings: string[] } {
  const warnings: string[] = [];

  const dumpedClients = clients.map((c) => {
    if (c.isConfidential) {
      warnings.push(`client '${c._id}' is confidential but dumped without a secret — add secret: \${ENV} before a fresh-db rebuild`);
    }
    return compact({
      id: c._id,
      name: c.name,
      grantTypes: c.grantTypes,
      audience: c.audience,
      redirectUris: c.redirectUris,
      scopes: c.scopes,
      isConfidential: c.isConfidential,
      subject: c.subject,
      claims: c.claims && Object.keys(c.claims).length ? c.claims : undefined
      // secret intentionally omitted — see file header.
    });
  });

  let dumpedUsers: Record<string, unknown>[] = [];
  if (opts.includeUsers) {
    dumpedUsers = users.map((u) => {
      warnings.push(`user '${u.email}' dumped with a \${${passwordEnvVar(u.email)}} placeholder — set it in the env before loading`);
      return compact({
        email: u.email,
        password: `\${${passwordEnvVar(u.email)}}`,
        status: u.status,
        roles: u.roles
      });
    });
  }

  return { clients: dumpedClients, users: dumpedUsers, warnings };
}

const HEADER =
  '# Generated by `npm run dump-seed` — a snapshot of the OAuth clients currently in the database.\n' +
  '# Client secrets and user passwords are NOT included (they are stored only as one-way hashes).\n' +
  '# Review, add any `secret: ${ENV}` refs needed for a fresh-db rebuild, then commit.\n\n';

/** Serialize built clients/users to a seed.yaml document (header comment + YAML body). */
export function toSeedYaml(seed: { clients: Record<string, unknown>[]; users: Record<string, unknown>[] }): string {
  const body: Record<string, unknown> = { clients: seed.clients };
  if (seed.users.length) body.users = seed.users;
  return HEADER + stringify(body);
}

async function main() {
  const flags = parseFlags();
  const connection = await getMasterConnection();
  const { OAuthClient, User } = makeModels(connection);

  const clients = await OAuthClient.find().sort({ _id: 1 }).lean().exec() as unknown as DumpClient[];
  const users = flags.includeUsers
    ? await User.find().sort({ email: 1 }).lean().exec() as unknown as DumpUser[]
    : [];

  const { clients: outClients, users: outUsers, warnings } = buildSeed(clients, users, { includeUsers: flags.includeUsers });
  const yamlBody = toSeedYaml({ clients: outClients, users: outUsers });

  if (flags.out) {
    writeFileSync(flags.out, yamlBody, 'utf-8');
    console.error(`dump-seed: wrote ${outClients.length} client(s) to ${flags.out}`);
  } else {
    process.stdout.write(yamlBody);
  }
  for (const w of warnings) console.error(`  warn: ${w}`);
}

// Only hit the database when run as a script — importing the pure helpers (tests) must not connect.
const invokedDirectly = process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1];
if (invokedDirectly) {
  main()
    .catch((err) => { console.error(err.message ?? err); process.exitCode = 1; })
    .finally(() => disconnect());
}
